#目标：依赖文件
#tab命令

a.out:add.o sub.o main.o mul.o div.o
	gcc add.o sub.o main.o mul.o div.o -o a.out

add.o:add.c
	gcc -c add.c -o add.o

sub.o:sub.c
	gcc -c sub.c -o sub.o

main.o:main.c
	gcc -c main.c -o main.o


mul.o:mul.c
	gcc -c mul.c -o mul.o


div.o:div.c
	gcc -c div.c -o div.o


